[workspace]
members = [
	"utils",
	"utils-derive",
	"day1",
	"day2",
	"day3",
	"day4",
	"day5",
	"day6",
	"day7",
	"day8",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
utils = { path = "utils" }
