[package]
name = "day3"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
utils = { workspace = true, optional = true }

[features]
default = ["utils"]
utils = ["dep:utils"]
